FROM python:3.11-slim

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir paho-mqtt psycopg2-binary

COPY listener.py .

CMD ["python", "listener.py"]